# NeoForge Mods configuration for Lit Spaceships
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="lit_spaceships"
version="0.1.0-alpha.1"
displayName="Lit Spaceships"
description='''
An advanced spaceship, energy shield, and naval combat mod for Minecraft 1.21.1 built on NeoForge 21.1.x.
'''

[[dependencies.lit_spaceships]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.209,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lit_spaceships]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
